name: CI MAUI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJECT_PATH: "MyStarterKit/MyStarterKit.csproj"
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 7
        uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0
        with:
          dotnet-version: 7.0.x
          
      - name: Generate version number using date and run number
        shell: pwsh
        id: version-creator
        run: |
          $buildDay = Get-Date -Format "yyyy.Mdd"
          $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
          echo "::set-output name=APP_VERSION::$ver"

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build MAUI Android
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -f net7.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: mauiStarterKit-android-ci-build
          path: MyStarterKit/bin/Release/net6.0-android/*Signed.a*

# MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 7
        uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0
        with:
          dotnet-version: 7.0.x
      # For WinUI builds
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
          
      - name: Generate version number using date and run number
        shell: pwsh
        id: version-creator
        run: |
          $buildDay = Get-Date -Format "yyyy.Mdd"
          $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
          echo "::set-output name=APP_VERSION::$ver"
          
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build MAUI Windows
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -f net7.0-windows10.0.19041.0

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: MyStarterKit-windows-ci-build
          path: MyStarterKit/bin/Release/net7.0-windows10.0.19041.0/win10-x64/AppPackages/MyStarterKit*/MyStarterKit*.msix

# MAUI iOS Build
  build-ios:
    runs-on: macos-12
    name: iOS Build
    steps:

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 7
        uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0
        with:
          dotnet-version: 7.0.x
          
      - name: Generate version number using date and run number
        id: version-creator
        shell: bash
        run: |
          buildDay=`date +%Y.%m%d`
          echo $buildDay
          runNum=${{ env.GITHUB_RUN_NUMBER }}
          ver="${buildDay}.${runNum}.0"
          echo $ver
          echo "APP_VERSION=$ver" >> $GITHUB_ENV
        
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build MAUI iOS
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release -f net7.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: MyStarterKit-ios-ci-build
          path: MyStarterKit/bin/Release/net7.0-ios/iossimulator-x64/**/*.app

# MAUI MacCatalyst Build
  build-mac:
    runs-on: macos-12
    name: MacCatalyst Build
    steps:
    
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 7
        uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0
        with:
          dotnet-version: 7.0.x
          
      - name: Generate version number using date and run number
        id: version-creator
        shell: bash
        run: |
          buildDay=`date +%Y.%m%d`
          echo $buildDay
          runNum=${{ env.GITHUB_RUN_NUMBER }}
          ver="${buildDay}.${runNum}.0"
          echo $ver
          echo "APP_VERSION=$ver" >> $GITHUB_ENV
          
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build MAUI MacCatalyst
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -f net7.0-maccatalyst --no-restore -p:BuildIpa=True

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: MyStarterKit-macos-ci-build
          path: MyStarterKit/bin/Release/net7.0-maccatalyst/maccatalyst-x64/publish/*.pkg
